
python:
    - 3.7
  
virtualenv:
    system_site_packages: true

before_install:
    - pip install --user ablog

script:
    - ablog build

after_success:
    - git config --global user.name "w.tknv"
    - git config --global user.email "rreedd555@gmail.com"
    - git config --global push.default simple
    - ablog deploy --push-quietly --github-token=TRAVIS_CI_DEPLOY -m="`git log -1 --pretty=%B`"